import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:df_builder/df_builder.dart';
import 'package:lighthouse/src/helpers/file.dart';
import 'package:lighthouse/src/helpers/yaml.dart';
import 'package:path/path.dart';
import 'package:recase/recase.dart';

final _yamlAssets = <String>[];

class AssetsMakeCommand extends Command {
  @override
  String get description => 'make assets class => Assets';

  @override
  String get name => 'assets:make';

  @override
  Future<void> run() async {
    /// load yaml assets

    _yamlAssets.addAll(getYamlAssets());

    /// assets.dart
    final dfBuilder = DartFileBuilder(
      topComments: ['/// ! This File is Generated by LH DO NOT EDIT 👑'],
      name: '',
      path: '',
    );

    final assetsClassBuilder = ClassBuilder(
      name: 'assets',
      getters: await buildClassGetters(
        dfBuilder: dfBuilder,
        path: 'assets',
        useStaticGetter: true,
      ),
    );
    dfBuilder.addClass(assetsClassBuilder);

    /// generated files
    if (!Directory('./lib/generated').existsSync()) {
      await Directory('./lib/generated').create();
    }
    final genFile = File('./lib/generated/assets.dart');
    if (await genFile.exists()) await genFile.delete();
    await genFile.writeAsString(dfBuilder.toString());
  }
}

Future<List<ClassGetter>> buildClassGetters({
  required DartFileBuilder dfBuilder,
  required String path,
  bool useStaticGetter = false,
}) async {
  final children = await loadDirectoryFiles(path);
  final getters = <ClassGetter>[];
  for (final child in children) {
    if (child is File) {
      getters.add(ClassGetter(
        comments: findFSTypeComment(child.path),
        type: 'String',
        name: findNameWithoutFormat(child.path),
        whatToReturn: '\'${child.path.replaceAll('\\', '/')}\'',
        isStatic: useStaticGetter,
      ));
    } else {
      /// it is a directory
      /// build the interface
      dfBuilder.addClass(
        await buildInterface(
          dfBuilder: dfBuilder,
          path: child.path,
        ),
      );
      getters.add(
        ClassGetter(
          comments: findFSTypeComment(child.path),
          isStatic: useStaticGetter,
          name: findNameWithoutFormat(child.path),
          type: buildInterfaceName(child.path.pathCase.split('/').last),
          whatToReturn:
              "${buildInterfaceName(child.path.pathCase.split('/').last)}()",
        ),
      );
    }
  }
  return getters;
}

String buildInterfaceName(String key) => '_${key.pascalCase}Interface';

Future<ClassBuilder> buildInterface({
  required String path,
  required DartFileBuilder dfBuilder,
}) async {
  final getters = await buildClassGetters(
    useStaticGetter: false,
    dfBuilder: dfBuilder,
    path: path,
  );

  return ClassBuilder(
    havePrivateConstructor: false,
    name: buildInterfaceName(path.pathCase.split('/').last),
    getters: getters,
  );
}

String findName(String path) => path.split(separator).last;
String findNameWithoutFormat(String path) {
  final name = findName(path).split('.').first;
  return name.camelCase;
}

String findFSTypeComment(String child) {
  late String fComment;

  final isDirPath = isDir(child);
  if (isDirPath) {
    final fName = findName(child);
    final result = fName.split('.').last;
    fComment = '/// * $result';
  } else {
    return '/// * Directory';
  }

  final isInAssets = _yamlAssets.where((p) => isParentDir(p, child)).isNotEmpty;

  return isInAssets
      ? fComment
      : '''$fComment
      @Deprecated('${child.replaceAll('\\', '/')} is not in your assets in pubspec.yaml')''';
}
