/// ! This File is Generated by LH DO NOT EDIT 👑
import 'package:nations/nations.dart';

class _GenderInterface {
  final String key;
  _GenderInterface(this.key);
  String get male => key.trMale;
  String get feMale => key.trFemale;
  String get defaultGender => key.gender;
}

class _AgeInterface {
  final String key;
  const _AgeInterface(this.key);
  String get toYoung => 'to_young'.tr;
  String get oldEnough => 'old_enough'.tr;
  String get veryOld => 'very_old'.tr;
}

class _ValidationInterface {
  final String key;
  const _ValidationInterface(this.key);
  String get email => 'email'.tr;
  String get password => 'password'.tr;
  _AgeInterface get age => _AgeInterface('age');
}

class Tr {
  Tr._();

  static String get packageName => 'package_name'.tr;
  static String get date => 'date'.tr;
  static String get time => 'time'.tr;
  static String get enter => 'enter'.tr;
  static String get edit => 'edit'.tr;
  static String get show => 'show'.tr;
  static String get delete => 'delete'.tr;
  static String get error => 'error'.tr;
  static String get internet => 'internet'.tr;
  static String get no => 'no'.tr;
  static String get yes => 'yes'.tr;
  static _GenderInterface get gender => _GenderInterface('gender');
  static _ValidationInterface get validation =>
      _ValidationInterface('validation');
}
