/// ! This File is Generated by LH DO NOT EDIT 👑

import 'package:nations/nations.dart';

class _GenderInterface{_GenderInterface(this.key,);String key ;
String get male => 'gender.male'.tr ;String get female => 'gender.female'.tr ;}class _PersonInterface{_PersonInterface(this.key,);String key ;
String get male => 'person.male'.tr ;String get female => 'person.female'.tr ;}class _AgeInterface{_AgeInterface(this.key,);String key ;
String get toYoung => 'validation.age.to_young'.tr ;String get oldEnough => 'validation.age.old_enough'.tr ;String get veryOld => 'validation.age.very_old'.tr ;}class _ValidationInterface{_ValidationInterface(this.key,);String key ;
String get email => 'validation.email'.tr ;String get password => 'validation.password'.tr ;_AgeInterface get age => _AgeInterface('age') ;}class Tr{Tr._();static String get packageName => 'package_name'.tr ;static String get date => 'date'.tr ;static String get time => 'time'.tr ;static String get enter => 'enter'.tr ;static String get edit => 'edit'.tr ;static String get show => 'show'.tr ;static String get delete => 'delete'.tr ;static String get error => 'error'.tr ;static String get internet => 'internet'.tr ;static String get no => 'no'.tr ;static String get yes => 'yes'.tr ;static _GenderInterface get gender => _GenderInterface('gender') ;static _PersonInterface get person => _PersonInterface('person') ;static _ValidationInterface get validation => _ValidationInterface('validation') ;}